apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: ap-south-1

vpc:
  id: vpc-094f2a9f171d7a889
  cidr: "192.168.0.0/16"
  subnets:
    public:
      ap-south-1a:
        id: subnet-0c96b30df3701bcbd
      ap-south-1b:
        id: subnet-0c8b48744fd2d6c12
    private:
      ap-south-1a:
        id: subnet-0434b75990b579207
      ap-south-1b:
        id: subnet-0e308eeadec465bc7

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true
